FtCoreBundle:
    resource: "@FtCoreBundle/Resources/config/routing.yml"
    prefix:   /core/
        
FtHomeBundle:
    resource: "@FtHomeBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: FtHomeBundle:Security:login }
    
login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
        
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
