FtHomeBundle_homepage:
    pattern:  /
    defaults: { _controller: FtHomeBundle:Default:index }

FtHomeBundle_faq:
    pattern:  /faq
    defaults: { _controller: FtHomeBundle:Default:faq }
    
FtHomeBundle_infotests:
    pattern:  /what_we_test
    defaults: { _controller: FtHomeBundle:Default:infoTests }
       
_newsletter_email:
    pattern:  /newsletter_email
    defaults: { _controller: FtHomeBundle:NewsletterEmail:index }
    
_orig:
    pattern:  /homepage_v1/
    defaults: { _controller: FtHomeBundle:HomepageV1:index }
    
_v2:
    pattern:  /homepage_v2/
    defaults: { _controller: FtHomeBundle:HomepageV2:index }

ft_request:
    pattern:  /ft_request/
    defaults: { _controller: FtHomeBundle:FtRequest:index }
        
_ft_request_go:
    pattern:  /report_request
    defaults: { _controller: FtHomeBundle:FtRequest:go }
    
_ft_request_ajax_get:
    pattern:  /report_request_ajax_get
    defaults: { _controller: FtHomeBundle:FtRequest:getReportAjax }

_ft_request_get:
    pattern:  /report_request_get
    defaults: { _controller: FtHomeBundle:FtRequest:getReport }
                
_ft_request_check_url:
    pattern:  /report_check_url
    defaults: { _controller: FtHomeBundle:FtRequest:checkSubmittedUrl }
        
ft_request_preview:
    pattern:  /ft_request_preview/{id}
    defaults: { _controller: FtHomeBundle:FtRequest:preview }
        
ft_request_deliver:
    pattern:  /ft_request_deliver/{id}
    defaults: { _controller: FtHomeBundle:FtRequest:deliver }
            
ft_request_run:
    pattern:  /ft_request_run/{id}
    defaults: { _controller: FtHomeBundle:FtRequest:run }
    
ft_request_admin_run:
    pattern:  /ft_request_admin_run/{id}
    defaults: { _controller: FtHomeBundle:FtRequest:adminRun }
    
ft_request_output_run:
    pattern:  /ft_request_output_run/{id}
    defaults: { _controller: FtHomeBundle:FtRequest:outputRun }

ft_request_edit:
    pattern:  /ft_request_edit/{id}
    defaults: { _controller: FtHomeBundle:FtRequest:edit }

ft_request_new:
    pattern:  /ft_request_new/
    defaults: { _controller: FtHomeBundle:FtRequest:new }

ft_request_create:
    pattern:  /ft_request_create/
    defaults: { _controller: FtHomeBundle:FtRequest:create }

ft_request_delete:
    pattern:  /ft_request_delete/{id}
    defaults: { _controller: FtHomeBundle:FtRequest:delete }

ft_request_show:
    pattern:  /ft_request_show/{id}
    defaults: { _controller: FtHomeBundle:FtRequest:show }

ft_request_update:
    pattern:  /ft_request_update/{id}
    defaults: { _controller: FtHomeBundle:FtRequest:update }
    
logger:
    pattern:  /logger/
    defaults: { _controller: FtHomeBundle:Log:index }
    
logger_show:
    pattern:  /logger_show/{id}
    defaults: { _controller: FtHomeBundle:Log:show }
