parameters:
    daughter: Josie
#    ft_core.example.class: Ft\CoreBundle\Example

services:
#    ft_core.example:
#        class: %ft_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
