parameters:
#    ft_admin.example.class: Ft\AdminBundle\Example

services:
#    ft_admin.example:
#        class: %ft_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
